name: Build BusinessIdiomsApp

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Compile
        run: g++ -o BusinessIdiomsApp.exe BusinessIdiomsApp.cpp
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BusinessIdiomsApp
          path: BusinessIdiomsApp.exe
